[versions]
coroutines = "1.10.2"
koin = "4.1.1" # dependency injection - https://insert-koin.io/
compose-foundation = "1.9.2"
compose-material3 = "1.9.0"
napier = "2.7.1" # logger - https://github.com/AAkira/Napier
navigation = "2.9.1"
viewmodel = "2.9.5"

# android
androidx-activityCompose = "1.11.0"
androidx-appCompat = "1.7.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-foundation" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewmodel" }
